### ISSUE TITLE
.cs files

### ISSUE THREAD

**Issue by Chris-Anime** [IVogel/tModUnpacker#3]
So, is this supposed to also extract the .cs files for the code, or only images? I tried it twice and only got images.

**Comment by knomigwen** [comment]
I have also found that it only exports the images, and no .cs files.  Is there a way around this?

**Comment by BlueCatGamer** [comment]
For some reason, it only exports .cs files on certain mods.

**Comment by IVogel** [comment]
You could just decompile .dll file.
For example, you can use [dotPeek](https://www.jetbrains.com/decompiler/) or [dnSpy](https://github.com/0xd4d/dnSpy).
But be aware, mod can be obfuscated.

**Comment by BlueCatGamer** [comment]
That works just fine, but sometimes using that method creates lots of errors in the code. It can easily be fixed with simple items, but with advanced stuff, it can be REALLY hard to. (or maybe I'm just missing a step here, I don't really know)

**Comment by IVogel** [comment]
Yes, you're right.
But I can't do anything about .cs files.
If mod dev. don't want them to be packed in to the mod - they will not be packed.
And only way to modify/obtain the code is disassemblers.

Unpacker unpacks .tmod files as is (except rawimg files, they're converted to png automatically)
